version: '3'

services:
  black-coffee-app:
    build: ../
    image: localhost:5000/black-coffee
    container_name: black-coffee-app
    restart: always
    volumes:
      - ../:/var/www/public

  vwa-nginx:
    image: nginx:1.21.3-alpine
    container_name: black-coffee-nginx
    ports:
       - 3132:80
    volumes:
      - ../:/var/www/public
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - black-coffee-app
    restart: always